### ISSUE TITLE
[BUG]: Android 실행 이슈

### ISSUE THREAD

**Issue by injang** [mj-studio-library/react-native-naver-map#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of @mj-studio/react-native-naver-map

1.0.11

### Version of react-native

0.73.4

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Simulator

### What architecture types of react native are you seeing the problem on?

New Architecture(Fabric)

### Version of device(android API, iOS OS version, etc...)

Android 34

### What happened?

ReadMe 설명대로 설치하였고 AndroieManifest, build.gradle 설정 완료 했으나 아래 에러가 발생합니다.

<img width="1377" alt="image" src="https://github.com/mj-studio-library/react-native-naver-map/assets/38967694/1ddf08e4-c0dc-4251-be1a-cda3c359c0e4">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
안녕하세요, 네이버 맵 SDK를 Maven Repository가 제대로 설정되지 않아 못 불러오는 현상으로 보입니다. [`build.gradle`](https://github.com/mj-studio-library/react-native-naver-map/blob/91705aa22e80794123a9a86089ce6842ee86cfc1/example/android/build.gradle#L21)이 링크와 같이 설정된 것 맞을까요?

```
allprojects {
    repositories {
        maven {
            url "https://repository.map.naver.com/archive/maven"
        }
    }
}
```
